#!/bin/bash

echo "mlsdc!"
dx=4096 
dt=0.25
zwei=2

for i in {1..4}
  do
  for j in {1..5}
  do
    ./FE_mlsdcFP abs_res_tol=1e-9 num_elements=$dx dt=$dt tend=0.5
    dt=$(echo "$dt / $zwei" |bc -l)
  done
  dt=0.25
  dx=$(echo "$dx * $zwei" |bc -l)
done
