#!/bin/bash

echo "mlsdc!"
dx=128
dt=1
zwei=2

for i in {1..6}
  do
  for j in {1..6}
  do
    ./FE_mlsdc num_elements=$dx abs_res_tol=1e-10 num_iters=40 dt=$dt tend=2
    dt=$(echo "$dt / $zwei" |bc -l)
  done
  dt=1
  dx=$(echo "$dx * $zwei" |bc -l)
done
